alias ll="ls -larth"
alias mmvn="mvn -s $HOME/.m2/my_settings.xml"
alias mci="mvn clean install"
alias mct="mvn clean test"
alias catalina="sh $HOME/Development/java/tomcat/bin/catalina.sh"
alias sbtjr="sbt --jrebel"
alias simplehttp="python -m SimpleHTTPServer"
alias git-root='cd $(git rev-parse --show-cdup)'
alias gre="git-recent"
alias chrome='open -a Google\ Chrome'
